### ISSUE TITLE
when will you release this code?

### ISSUE THREAD

**Issue by BinbinBian** [yicheng-w/CommonSenseMultiHopQA#2]

**Comment by yicheng-w** [comment]
Sorry for the delay, unfortunately right now we are very busy with the upcoming NAACL deadline, but we'll release code right after.

**Comment by impredicative** [comment]
This issue is a duplicate and it should therefore it can probably be closed right away.

**Comment by machilusZ** [comment]
DDL of NAACL is passed, and rebuttal is months away. Could the authors release the code?

**Comment by yicheng-w** [comment]
Code & models have been released.
