### ISSUE TITLE
Python 2? Are you serious?

### ISSUE THREAD

**Issue by impredicative** [yicheng-w/CommonSenseMultiHopQA#3]
The expiration of Python 2 is less than a year away, but here you are, still using it for this new project. Refer to https://pythonclock.org/ . Please update the code to ensure it works with the latest Python 3.

**Comment by jiangnanhugo** [comment]
@impredicative  I don't think this matter. Probably you can do it.

**Comment by yicheng-w** [comment]
@impredicative this repository is not being actively maintained. But I'd gladly welcome a PR that'd bring it into python 3.
